version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: postgres_rural
    environment:
      POSTGRES_DB: rural_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    container_name: rural_api
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: rural_db
    depends_on:
      - db
    command: npm run start:prod

volumes:
  pgdata: